"use client";
import Image from "next/image";
import Link from "next/link";
import { ArrowLeft, CheckCircle2, Send } from "lucide-react";
import { useState, type FormEvent } from "react";
import { firebaseEnabled } from "@/lib/firebase";
import { submitApplication, type ApplicationPayload } from "@/lib/application";

const initial:ApplicationPayload={fullName:"",cpf:"",birthDate:"",email:"",phone:"",whatsapp:"",cep:"",address:"",number:"",district:"",city:"Blumenau",state:"SC",cnh:"",cnhCategory:"A",cnhExpiry:"",motorcyclePlate:"",motorcycleModel:"",motorcycleYear:"",notes:"",consent:false};
export function ApplicationForm(){const [data,setData]=useState(initial);const [busy,setBusy]=useState(false);const [message,setMessage]=useState<{type:"success"|"error";text:string}|null>(null);const update=(name:keyof ApplicationPayload,value:string|boolean)=>setData(v=>({...v,[name]:value}));
async function send(e:FormEvent){e.preventDefault();setBusy(true);setMessage(null);try{if(data.cpf.replace(/\D/g,"").length!==11)throw new Error("Informe um CPF com 11 dígitos.");if(!data.consent)throw new Error("É necessário aceitar os termos e a política de privacidade.");if(firebaseEnabled){const id=await submitApplication(data);setMessage({type:"success",text:`Cadastro enviado com sucesso. Protocolo: ${id.slice(0,12).toUpperCase()}.`});setData(initial)}else{setMessage({type:"success",text:"Demonstração validada. Configure o Firebase para gravar o cadastro de forma definitiva."})}}catch(err){setMessage({type:"error",text:err instanceof Error?err.message:"Não foi possível enviar."})}finally{setBusy(false)}}
return <main className="form-shell"><div className="container form-wrap"><aside className="form-aside"><Link href="/"><ArrowLeft size={17}/> Voltar ao site</Link><Image src="/logo.png" width={92} height={92} alt="AUMM"/><h2>Junte-se à AUMM</h2><p>Preencha seus dados com atenção. O envio inicia uma análise e não ativa automaticamente a associação.</p><div className="steps"><span><i>1</i> Envie seus dados</span><span><i>2</i> Aguarde a análise</span><span><i>3</i> Receba a confirmação</span></div></aside><form className="application-form" onSubmit={send}><div className="form-heading"><div><h1>Solicitação de associação</h1><p>Campos com * são obrigatórios.</p></div><span className="demo-badge">Ambiente {firebaseEnabled?"conectado":"demonstrativo"}</span></div>
<FormSection title="Dados pessoais"><Field label="Nome completo *" name="fullName" value={data.fullName} onChange={update} required/><Field label="CPF *" name="cpf" value={data.cpf} onChange={update} required placeholder="000.000.000-00"/><Field label="Data de nascimento *" name="birthDate" type="date" value={data.birthDate} onChange={update} required/><Field label="E-mail *" name="email" type="email" value={data.email} onChange={update} required/><Field label="Telefone *" name="phone" value={data.phone} onChange={update} required/><Field label="WhatsApp *" name="whatsapp" value={data.whatsapp} onChange={update} required/></FormSection>
<FormSection title="Endereço"><Field label="CEP *" name="cep" value={data.cep} onChange={update} required/><Field label="Endereço *" name="address" value={data.address} onChange={update} required/><Field label="Número *" name="number" value={data.number} onChange={update} required/><Field label="Bairro *" name="district" value={data.district} onChange={update} required/><Field label="Cidade *" name="city" value={data.city} onChange={update} required/><Field label="Estado *" name="state" value={data.state} onChange={update} required maxLength={2}/></FormSection>
<FormSection title="CNH e motocicleta"><Field label="Número da CNH *" name="cnh" value={data.cnh} onChange={update} required/><label className="field"><span>Categoria da CNH *</span><select value={data.cnhCategory} onChange={e=>update("cnhCategory",e.target.value)}><option>A</option><option>AB</option><option>AC</option><option>AD</option><option>AE</option></select></label><Field label="Validade da CNH *" name="cnhExpiry" type="date" value={data.cnhExpiry} onChange={update} required/><Field label="Placa da motocicleta *" name="motorcyclePlate" value={data.motorcyclePlate} onChange={update} required/><Field label="Modelo da motocicleta *" name="motorcycleModel" value={data.motorcycleModel} onChange={update} required/><Field label="Ano *" name="motorcycleYear" value={data.motorcycleYear} onChange={update} required/></FormSection>
<div className="form-section"><h2>Documentos e observações</h2><div className="form-grid"><div className="field full"><span>Foto e documentos</span><small>Os documentos serão solicitados pela AUMM durante a análise. O plano gratuito não armazena anexos.</small></div><label className="field full"><span>Observações</span><textarea value={data.notes} onChange={e=>update("notes",e.target.value)} /></label></div></div>
<label className="consent"><input type="checkbox" checked={data.consent} onChange={e=>update("consent",e.target.checked)}/><span>Li e aceito a <Link className="text-link" href="/privacidade">Política de Privacidade</Link>, autorizo o tratamento dos dados para análise da associação e declaro que as informações são verdadeiras.</span></label>{message&&<div className={`form-message ${message.type}`}>{message.type==="success"&&<CheckCircle2 size={16}/>} {message.text}</div>}<button className="button" disabled={busy}>{busy?"Enviando...":<>Enviar solicitação <Send size={17}/></>}</button></form></div></main>}
function FormSection({title,children}:{title:string;children:React.ReactNode}){return <div className="form-section"><h2>{title}</h2><div className="form-grid">{children}</div></div>}
function Field({label,name,value,onChange,type="text",...props}:{label:string;name:keyof ApplicationPayload;value:string;onChange:(n:keyof ApplicationPayload,v:string)=>void;type?:string;required?:boolean;placeholder?:string;maxLength?:number}){return <label className="field"><span>{label}</span><input {...props} type={type} value={value} onChange={e=>onChange(name,e.target.value)}/></label>}
