"use client";
import { FormEvent,useEffect,useMemo,useState } from "react";
import { onAuthStateChanged } from "firebase/auth";
import { collection,doc,getDoc,limit,onSnapshot,orderBy,query } from "firebase/firestore";
import { Archive,ExternalLink,FilePlus2,Search,Send } from "lucide-react";
import { getFirebaseServices } from "@/lib/firebase";
import { archiveInstitutionalDocument,createInstitutionalDocument,publishInstitutionalDocument,updateSignedDocument,type DocumentDraft } from "@/lib/documentService";
import { DOCUMENT_CATEGORIES,DOCUMENT_CATEGORY_NAMES,type InstitutionalDocument } from "@/lib/documentTypes";
import type { AssemblyActor } from "@/lib/assemblyService";

const initial={category:"institutional",title:"",description:"",documentNumber:"",year:String(new Date().getFullYear()),documentDate:new Date().toISOString().slice(0,10),sourceType:"external",url:"",visibility:"public",statuteVersion:"",signedDocumentUrl:""};
export function DocumentAdmin(){const[actor,setActor]=useState<AssemblyActor|null>(null),[rows,setRows]=useState<InstitutionalDocument[]>([]),[form,setForm]=useState(initial),[search,setSearch]=useState(""),[message,setMessage]=useState("");
 useEffect(()=>{const{auth,db}=getFirebaseServices();const a=onAuthStateChanged(auth,async u=>{if(!u)return;const role=await getDoc(doc(db,"adminRoles",u.uid));setActor({uid:u.uid,name:u.displayName||u.email||"Administrador",role:String(role.data()?.role||"Administrador")});});const d=onSnapshot(query(collection(db,"documents"),orderBy("createdAt","desc"),limit(50)),s=>setRows(s.docs.map(x=>({id:x.id,...x.data()}) as InstitutionalDocument)),e=>setMessage(e.message));return()=>{a();d();}},[]);
 const filtered=useMemo(()=>rows.filter(x=>`${x.title} ${x.documentNumber||""} ${x.year} ${DOCUMENT_CATEGORY_NAMES[x.category]||x.category}`.toLowerCase().includes(search.toLowerCase())),[rows,search]);
 async function submit(e:FormEvent){e.preventDefault();if(!actor)return;try{const url=form.url.trim();const input:DocumentDraft={category:form.category,title:form.title,description:form.description,documentNumber:form.documentNumber,year:Number(form.year),documentDate:new Date(`${form.documentDate}T12:00:00-03:00`),sourceType:form.sourceType as DocumentDraft["sourceType"],internalUrl:form.sourceType==="internal"?url:"",externalUrl:form.sourceType==="external"?url:"",sourceId:"",visibility:form.visibility as DocumentDraft["visibility"],status:"draft",published:false,isCurrent:false,statuteVersion:form.statuteVersion,signedDocumentUrl:form.signedDocumentUrl};await createInstitutionalDocument(input,actor);setForm(initial);setMessage("Documento salvo como rascunho.");}catch(e){setMessage(e instanceof Error?e.message:"Falha ao salvar.");}}
 return <div className="document-admin"><section className="panel"><div className="panel-head"><div><h3><FilePlus2 size={18}/> Novo documento</h3><p>Cadastre metadados e uma URL; PDFs e scans não são gravados no Firestore.</p></div></div><form onSubmit={submit}><div className="form-grid"><label className="field"><span>Categoria</span><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{DOCUMENT_CATEGORIES.map(x=><option key={x} value={x}>{DOCUMENT_CATEGORY_NAMES[x]}</option>)}</select></label><label className="field"><span>Visibilidade</span><select value={form.visibility} onChange={e=>setForm({...form,visibility:e.target.value})}><option value="public">Público</option><option value="members">Somente associados</option><option value="admin">Somente administração</option></select></label><label className="field full"><span>Título</span><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label className="field full"><span>Descrição/assuntos</span><textarea required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label className="field"><span>Data</span><input type="date" required value={form.documentDate} onChange={e=>setForm({...form,documentDate:e.target.value})}/></label><label className="field"><span>Número</span><input value={form.documentNumber} onChange={e=>setForm({...form,documentNumber:e.target.value})} placeholder="04/2026"/></label><label className="field"><span>Ano</span><input type="number" value={form.year} onChange={e=>setForm({...form,year:e.target.value})}/></label><label className="field"><span>Versão do Estatuto</span><input value={form.statuteVersion} onChange={e=>setForm({...form,statuteVersion:e.target.value})}/></label><label className="field"><span>Origem</span><select value={form.sourceType} onChange={e=>setForm({...form,sourceType:e.target.value})}><option value="internal">Arquivo interno do site</option><option value="external">Link externo/Google Drive</option></select></label><label className="field"><span>Caminho/URL</span><input required value={form.url} onChange={e=>setForm({...form,url:e.target.value})} placeholder="/documentos/...pdf ou https://drive.google.com/..."/></label><label className="field full"><span>Documento assinado/registrado (opcional)</span><input value={form.signedDocumentUrl} onChange={e=>setForm({...form,signedDocumentUrl:e.target.value})}/></label></div>{form.sourceType==="external"&&<p className="document-warning">A AUMM não controla o acesso direto a uma URL pública externa. Confira as permissões no Google Drive.</p>}<div className="assembly-actions"><button className="button"><FilePlus2 size={15}/> Salvar rascunho</button>{form.url&&<a className="button button-sm button-dark" href={form.url} target="_blank" rel="noreferrer"><ExternalLink size={14}/> Testar link</a>}</div></form>{message&&<div className="form-message">{message}</div>}</section>
 <section className="panel"><label className="admin-search"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por título, número, ano ou categoria"/></label><div className="document-admin-list">{filtered.length===0?<div className="empty-state">Nenhum documento cadastrado.</div>:filtered.map(item=><article className="document-card" key={item.id}><div><span>{DOCUMENT_CATEGORY_NAMES[item.category]||item.category}</span><h3>{item.title}</h3><p>{item.description}</p><small>{item.documentNumber||item.year} · {item.visibility} · {item.status}</small></div><div className="assembly-actions">{!item.published&&<button className="button button-sm" onClick={async()=>{if(!actor)return;const current=item.category==="statute"&&window.confirm("Marcar este Estatuto como vigente e substituir o atual?");await publishInstitutionalDocument(item,actor,current);}}> <Send size={14}/> Publicar</button>}{item.published&&<button className="button button-sm button-dark" onClick={()=>actor&&window.confirm("Arquivar este documento publicado?")&&archiveInstitutionalDocument(item,actor)}><Archive size={14}/> Arquivar</button>}<button className="button button-sm button-dark" onClick={()=>{const url=window.prompt("URL da versão assinada/registrada:",item.signedDocumentUrl||"");if(url&&actor)updateSignedDocument(item,url,actor);}}>Vincular assinado</button></div></article>)}</div></section></div>}
