"use client";
import { useEffect,useMemo,useState } from "react";
import { collection,limit,onSnapshot,orderBy,query,where } from "firebase/firestore";
import { ExternalLink,FileText,Printer,Search } from "lucide-react";
import { getFirebaseServices } from "@/lib/firebase";
import { withBasePath } from "@/lib/paths";
import { DOCUMENT_CATEGORY_NAMES,type InstitutionalDocument } from "@/lib/documentTypes";

export function DocumentLibrary({member=false}:{member?:boolean}){const[rows,setRows]=useState<InstitutionalDocument[]>([]),[search,setSearch]=useState(""),[category,setCategory]=useState("all"),[selected,setSelected]=useState<InstitutionalDocument|null>(null);
 useEffect(()=>{const{db}=getFirebaseServices();return onSnapshot(query(collection(db,"documents"),where("published","==",true),where("visibility","in",member?["public","members"]:["public"]),orderBy("documentDate","desc"),limit(50)),s=>setRows(s.docs.map(x=>({id:x.id,...x.data()}) as InstitutionalDocument)));},[member]);
 const shown=useMemo(()=>rows.filter(x=>(category==="all"||x.category===category)&&`${x.title} ${x.documentNumber||""} ${x.year}`.toLowerCase().includes(search.toLowerCase())),[rows,search,category]);const current=rows.find(x=>x.category==="statute"&&x.isCurrent);
 const openUrl=(x:InstitutionalDocument)=>x.internalUrl?withBasePath(x.internalUrl):x.externalUrl||x.signedDocumentUrl||"";
 return <div className="document-library">{current&&<section className="current-statute"><FileText/><div><span>Estatuto vigente</span><h2>{current.title}</h2><p>Versão {current.statuteVersion||current.year}</p></div><button className="button" onClick={()=>setSelected(current)}>Visualizar</button></section>}<div className="document-filters"><label className="admin-search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Pesquisar documentos"/></label><select value={category} onChange={e=>setCategory(e.target.value)}><option value="all">Todas as categorias</option>{Object.entries(DOCUMENT_CATEGORY_NAMES).map(([id,name])=><option value={id} key={id}>{name}</option>)}</select></div><div className="document-grid">{shown.length===0?<div className="empty-state">Nenhum documento publicado nesta categoria.</div>:shown.map(x=><article className="document-public-card" key={x.id}><span>{DOCUMENT_CATEGORY_NAMES[x.category]||x.category}</span><h3>{x.title}</h3><p>{x.description}</p><small>{x.documentNumber||x.year} · {x.documentDate?.toDate().toLocaleDateString("pt-BR")}</small><div className="assembly-actions"><button className="button button-sm" onClick={()=>setSelected(x)}>Visualizar</button>{openUrl(x)&&<a className="button button-sm button-dark" href={openUrl(x)} target="_blank" rel="noreferrer"><ExternalLink size={14}/> Abrir documento</a>}{x.signedDocumentUrl&&<a className="button button-sm button-dark" href={x.signedDocumentUrl} target="_blank" rel="noreferrer">Documento assinado</a>}</div></article>)}</div>{selected&&<div className="document-modal" role="dialog" aria-modal="true"><article><button className="modal-close" onClick={()=>setSelected(null)}>×</button><span>{DOCUMENT_CATEGORY_NAMES[selected.category]}</span><h1>{selected.title}</h1><p>{selected.description}</p><dl><div><dt>Número/ano</dt><dd>{selected.documentNumber||selected.year}</dd></div><div><dt>Visibilidade</dt><dd>{selected.visibility}</dd></div><div><dt>Fonte</dt><dd>{selected.sourceType}</dd></div></dl>{selected.sourceType==="assembly_minutes"&&<p>Ata eletrônica vinculada à Assembleia {selected.sourceId}. Consulte o histórico no Portal do Associado para pautas, resultados e hash.</p>}<div className="assembly-actions">{openUrl(selected)&&<a className="button" href={openUrl(selected)} target="_blank" rel="noreferrer">Visualizar documento</a>}<button className="button button-dark" onClick={()=>window.print()}><Printer size={15}/> Imprimir / PDF</button></div></article></div>}</div>}
