"use client";
import Image from "next/image";
import Link from "next/link";
import { signInWithEmailAndPassword, sendPasswordResetEmail } from "firebase/auth";
import { useRouter, useSearchParams } from "next/navigation";
import { useState,type FormEvent } from "react";
import { LockKeyhole, LogIn, Mail } from "lucide-react";
import { firebaseEnabled,getFirebaseServices } from "@/lib/firebase";
import { doc, getDoc } from "firebase/firestore";
export function LoginForm(){const router=useRouter();const params=useSearchParams();const admin=params.get("destino")==="admin";const denied=params.get("erro")==="acesso";const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [error,setError]=useState(denied?admin?"Este usuário não possui acesso administrativo.":"Seu cadastro ainda não está autorizado para acessar o portal.":"");const [busy,setBusy]=useState(false);async function login(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{if(firebaseEnabled){const {auth,db}=getFirebaseServices();const cred=await signInWithEmailAndPassword(auth,email,password);if(admin){const access=await getDoc(doc(db,"adminRoles",cred.user.uid));if(!access.exists()||access.data().active!==true)throw new Error("Este usuário não possui acesso administrativo.")}router.push(admin?"/admin":"/associado")}else router.push(admin?"/admin":"/associado")}catch(err){setError(err instanceof Error?err.message:"Falha ao entrar.")}finally{setBusy(false)}}async function reset(){if(!email){setError("Informe seu e-mail primeiro.");return}try{await sendPasswordResetEmail(getFirebaseServices().auth,email);setError("E-mail de recuperação enviado.")}catch{setError("Não foi possível enviar a recuperação.")}}
return <main className="auth-page"><section className="auth-brand"><Link className="auth-logo" href="/"><Image src="/logo.png" width={78} height={78} alt="AUMM"/><strong>AUMM</strong></Link><div><h1>Sua associação.<br/>Sempre com você.</h1><p>Acesse sua carteirinha, benefícios, comunicados e solicitações em um só lugar.</p></div><small>Área protegida · Blumenau/SC</small></section><section className="auth-panel"><div className="auth-card"><span className="eyebrow">Acesso seguro</span><h2>{admin?"Administração":"Área do associado"}</h2><p>Use o e-mail cadastrado na AUMM.</p>{!firebaseEnabled&&<div className="demo-badge">Modo demonstração — qualquer acesso</div>}<form onSubmit={login}><label className="field"><span><Mail size={14}/> E-mail</span><input type="email" value={email} onChange={e=>setEmail(e.target.value)} required placeholder="seu@email.com"/></label><label className="field"><span><LockKeyhole size={14}/> Senha</span><input type="password" value={password} onChange={e=>setPassword(e.target.value)} required placeholder="Sua senha"/></label>{error&&<div className="form-message error">{error}</div>}<button className="button" disabled={busy}>{busy?"Entrando...":<>Entrar <LogIn size={16}/></>}</button></form><div className="auth-links"><button onClick={reset}>Esqueci minha senha</button><Link href="/associe-se">Quero me associar</Link></div><div className="auth-links"><Link href="/">← Voltar ao site</Link><Link href={admin?"/associado/login":"/associado/login?destino=admin"}>{admin?"Portal do associado":"Acesso administrativo"}</Link></div></div></section></main>}
